global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'consul_registered_services'
    scrape_interval: 5s
    metrics_path: '/api/v1/actuator/prometheus'
    consul_sd_configs:
      - server: 'consul:8500'
    relabel_configs:
      - source_labels: ['__meta_consul_tags']
        regex: ',,'
        action: drop
      - source_labels: ['__meta_consul_service']
        regex:         '(ap-.*)'
        target_label:  'application'
        replacement:   '$1'
